#!/usr/bin/env bash

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Install other useful binaries
brew install ack
brew install git
brew install lynx
brew install node
brew install vim --with-lua
brew install macvim --with-lua

brew install rbenv
brew install ruby-build

brew install z

brew install zsh

brew tap homebrew/versions
brew install lua52

# Install native apps
brew tap phinze/homebrew-cask
brew install brew-cask

function installcask() {
  brew cask install "${@}" 2> /dev/null
}

installcask dropbox
installcask imageoptim
installcask iterm2
installcask the-unarchiver
installcask virtualbox
installcask vlc
installcask spectacle

# Remove outdated versions from the cellar
brew cleanup
