#!/usr/bin/env bash

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Install other useful binaries
brew install ack
brew install lynx
brew install node
brew install vim --with-lua
brew install macvim --with-lua

brew install the_silver_searcher

brew install rbenv
brew install ruby-build

brew install z

brew install zsh

brew tap homebrew/versions
brew install lua52

# Install native apps
brew tap phinze/homebrew-cask
brew install brew-cask

function installcask() {
  brew cask install "${@}" 2> /dev/null
}

installcask dropbox
installcask google-chrome
installcask imageoptim
installcask iterm2
installcask the-unarchiver
installcask virtualbox
installcask vlc
installcask spectacle
installcask kaleidoscope
installcask firefox
installcask vagrant
installcask evernote
installcask spotify

# Remove outdated versions from the cellar
brew cleanup

# oh-my-zsh
curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh

# vundle
git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
vim +BundleInstall +qall
