#!/usr/bin/env bash

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Install other useful binaries
brew install ack
brew install git
brew install node
brew install vim --with-lua
brew install macvim --with-lua

brew install zsh

brew tap homebrew/versions
brew install lua52

# Install native apps
brew install caskroom/cask/brew-cask

function installcask() {
  brew cask install "${@}" 2> /dev/null
}

installcask dropbox
installcask imageoptim
installcask iterm2-nightly
installcask the-unarchiver
installcask virtualbox
installcask vlc
installcask kaleidoscope
installcask firefox

# Remove outdated versions from the cellar
brew cleanup

# Eslint
npm i -g eslint babel-eslint eslint-plugin-react

# vundle
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim +BundleInstall +qall
