#!/usr/bin/env bash

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Install other useful binaries
brew install ack
brew install git
brew install node
brew install vim --with-lua
brew install macvim --with-lua

# for the lolz
brew install fortune
brew install cowthink

brew install zsh
brew install tmux

brew tap homebrew/versions
brew install lua52

brew install thefuck
brew install reattach-to-user-namespace --wrap-pbcopy-and-pbpaste

# https://github.com/defunkt/gist
brew install gist

# Install native apps
brew install caskroom/cask/brew-cask

# Gist
brew install gist

# Enable beta, nightly, etc. installs
brew tap caskroom/versions

# Install fish
brew install fish
# Make default shell
echo "/usr/local/bin/fish" | sudo tee -a /etc/shells

function installcask() {
  brew cask install "${@}" 2> /dev/null
}

installcask dropbox
installcask iterm2-nightly
installcask the-unarchiver
installcask virtualbox
installcask vlc

# Remove outdated versions from the cellar
brew cleanup

# Eslint
npm i -g eslint babel-eslint eslint-plugin-react

# vim-plug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim +PlugInstall +qall

# tmux plugin manager
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

#nvim
brew tap neovim/neovim
brew install --HEAD neovim

#fix for C-H
infocmp $TERM | sed 's/kbs=^[hH]/kbs=\\177/' > $TERM.ti && tic $TERM.ti
